### ISSUE TITLE
您好,Demo写的非常不错了,不过,代码好像没有提交完整哦,运行项目有两处小问题,可以重新提交一次就更完美了!不嫌弃可以加QQ569015640交流

### ISSUE THREAD

**Issue by MicroKibaco** [songxiaoliang/ReactNativeApp#1]
**清单文件已添加权限报错:但是触发拨打电话引起的Exception**

> 05-03 17:20:14.314 24958-25028/com.example.song.reactnativeappdemo E/unknown:React: Exception in native call java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.CALL dat=tel:xxxxxxxxxxx flg=0x10000000 cmp=com.android.server.telecom/.components.UserCallActivity } from ProcessRecord{9ba8f5f 24958:com.example.song.reactnativeappdemo/u0a172} (pid=24958, uid=10172) with revoked permission android.permission.CALL_PHONE at android.os.Parcel.readException(Parcel.java:1683) at android.os.Parcel.readException(Parcel.java:1636) at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3071) at android.app.Instrumentation.execStartActivity(Instrumentation.java:1518) at android.app.ContextImpl.startActivity(ContextImpl.java:819) at android.app.ContextImpl.startActivity(ContextImpl.java:796) at android.content.ContextWrapper.startActivity(ContextWrapper.java:356) at android.content.ContextWrapper.startActivity(ContextWrapper.java:356) at com.example.song.reactnativeappdemo.communication.CommModule.rnCallNative(CommModule.java:53) at java.lang.reflect.Method.invoke(Native Method) at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319) at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) at android.os.Looper.loop(Looper.java:154) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) at java.lang.Thread.run(Thread.java:761)

_----------------------------------------------------------------------------------------------_
**触发向RN发送消息引发的Bug**
> Process: com.example.song.reactnativeappdemo, PID: 23227 java.lang.IllegalStateException: Could not execute method for android:onClick at android.view.View$DeclaredOnClickListener.onClick(View.java:4697) at android.view.View.performClick(View.java:5609) at android.view.View$PerformClick.run(View.java:22262) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6077) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) Caused by: java.lang.reflect.InvocationTargetException at java.lang.reflect.Method.invoke(Native Method) at android.view.View$DeclaredOnClickListener.onClick(View.java:4692) at android.view.View.performClick(View.java:5609)  at android.view.View$PerformClick.run(View.java:22262)  at android.os.Handler.handleCallback(Handler.java:751)  at android.os.Handler.dispatchMessage(Handler.java:95)  at android.os.Looper.loop(Looper.java:154)  at android.app.ActivityThread.main(ActivityThread.java:6077)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.song.reactnativeappdemo.communication.CommModule.nativeCallRn(java.lang.String)' on a null object reference at com.example.song.reactnativeappdemo.MainActivity.sendMsgToRN(MainActivity.java:43) at java.lang.reflect.Method.invoke(Native Method)  at android.view.View$DeclaredOnClickListener.onClick(View.java:4692)  at android.view.View.performClick(View.java:5609)  at android.view.View$PerformClick.run(View.java:22262)  at android.os.Handler.handleCallback(Handler.java:751)  at android.os.Handler.dispatchMessage(Handler.java:95)  at android.os.Looper.loop(Looper.java:154)  at android.app.ActivityThread.main(ActivityThread.java:6077)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by MicroKibaco** [comment]
**加载最新 BUNDLE 在Android7.0 上的报错**

> 05-03 17:28:31.556 32748-32748/com.example.song.reactnativeappdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: com.example.song.reactnativeappdemo, PID: 32748
                                                                                     java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                         at android.view.View$DeclaredOnClickListener.onClick(View.java:4697)
                                                                                         at android.view.View.performClick(View.java:5609)
                                                                                         at android.view.View$PerformClick.run(View.java:22262)
                                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at android.view.View$DeclaredOnClickListener.onClick(View.java:4692)
                                                                                         at android.view.View.performClick(View.java:5609) 
                                                                                         at android.view.View$PerformClick.run(View.java:22262) 
                                                                                         at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                                      Caused by: java.lang.SecurityException: No permission to write to /storage/emulated/0/com.example.song.reactnativeappdemo/patch.zip: Neither user 10172 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
                                                                                         at android.os.Parcel.readException(Parcel.java:1683)
                                                                                         at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                                         at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                                         at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
                                                                                         at android.content.ContentResolver.insert(ContentResolver.java:1274)
                                                                                         at android.app.DownloadManager.enqueue(DownloadManager.java:1014)
                                                                                         at com.example.song.reactnativeappdemo.MainActivity.downLoadBundle(MainActivity.java:91)
                                                                                         at com.example.song.reactnativeappdemo.MainActivity.checkVersion(MainActivity.java:70)
                                                                                         at com.example.song.reactnativeappdemo.MainActivity.load(MainActivity.java:59)
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at android.view.View$DeclaredOnClickListener.onClick(View.java:4692) 
                                                                                         at android.view.View.performClick(View.java:5609) 
                                                                                         at android.view.View$PerformClick.run(View.java:22262) 
                                                                                         at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by MicroKibaco** [comment]
>     if (true) {
                    
                    Toast.makeText(this, "开始下载", Toast.LENGTH_SHORT).show();
                    downLoadBundle();

                } 还有一个小问题 这行代码........

**Comment by songxiaoliang** [comment]
三个问题基本都跟适配相关。第一个问题原因：需要动态申请权限。后两个问题原因：Android7.0中在XML布局中设置onClick会与Theme主题有相互关系。XML中设置了，就不要对单个Acty设置Theme。一般建议直接改成setOnClickListener注册方式。

**Comment by longkehuawei** [comment]
我更新第一个zip没有问题，然后再下载另外一个zip覆盖就有问题了

**Comment by longkehuawei** [comment]
Unexpected number '0'

**Comment by songxiaoliang** [comment]
@longkehuawei 热更新吗？

**Comment by longkehuawei** [comment]
1.zip更新，然后再用2.zip更新就有问题
